### ISSUE TITLE
compile error " sr_get_changes"

### ISSUE THREAD

**Issue by olegzharov** [sysrepo/sysrepo-cpp#11]
Hi!
I've got an error when start to build this:

_[vmware@srv-01 build]$ make
[  5%] Building CXX object CMakeFiles/sysrepo-cpp.dir/src/Connection.cpp.o
[ 11%] Building CXX object CMakeFiles/sysrepo-cpp.dir/src/Enum.cpp.o
[ 16%] Building CXX object CMakeFiles/sysrepo-cpp.dir/src/Session.cpp.o
/home/vmware/sysrepo-cpp-master/src/Session.cpp: In member function ‘std::optional<const libyang::DataNode> sysrepo::Session::getPendingChanges() const’:
/home/vmware/sysrepo-cpp-master/src/Session.cpp:217:20: error: ‘sr_get_changes’ was not declared in this scope; did you mean ‘sr_has_changes’?
  217 |     auto changes = sr_get_changes(m_sess.get());
      |                    ^~~~~~~~~~~~~~
      |                    sr_has_changes
/home/vmware/sysrepo-cpp-master/src/Session.cpp: At global scope:
/home/vmware/sysrepo-cpp-master/src/Session.cpp:573:2: warning: extra ‘;’ [-Wpedantic]
  573 | };
      |  ^
make[2]: *** [CMakeFiles/sysrepo-cpp.dir/src/Session.cpp.o] Error 1
make[1]: *** [CMakeFiles/sysrepo-cpp.dir/all] Error 2
make: *** [all] Error 2
_

Can you please help with this issue?

**Comment by michalvasko** [comment]
On a release `devel` is merged into `master` so in both, currently.
