### ISSUE TITLE
utils compile error

### ISSUE THREAD

**Issue by olegzharov** [sysrepo/sysrepo-cpp#12]
_[ 38%] Built target sysrepo-cpp
[ 44%] Building CXX object CMakeFiles/DoctestIntegration.dir/tests/doctest-integration.cpp.o
[ 50%] Building CXX object CMakeFiles/DoctestIntegration.dir/tests/utils.cpp.o
/home/vmware/sysrepo-cpp-master/tests/utils.cpp:14:10: fatal error: trompeloeil.hpp: No such file or directory
   14 | #include <trompeloeil.hpp>
      |          ^~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/DoctestIntegration.dir/tests/utils.cpp.o] Error 1
make[1]: *** [CMakeFiles/DoctestIntegration.dir/all] Error 2
make: *** [all] Error 2
_

Does it depend from https://github.com/rollbear/trompeloeil ? Should I install that one as well?

**Comment by jktjkt** [comment]
Thanks for reporting this, our docs were incomplete. Here are the patches if you would like to test them:

- https://gerrit.cesnet.cz/c/CzechLight/sysrepo-cpp/+/5742
- https://gerrit.cesnet.cz/c/CzechLight/sysrepo-cpp/+/5743
