### ISSUE TITLE
EditOptions vs sr_edit_flag_t

### ISSUE THREAD

**Issue by jjin62** [sysrepo/sysrepo-cpp#14]
By wrapping sr_edit_flag_t with a Enum, seems I can not set multiple edit flags anymore, since options in Enum EditOptions are mutual-exclusive. How should deal with this?

Similarly, we would have the same issue if I wrap sr_get_oper_flag_t using a Enum?

**Comment by jktjkt** [comment]
I'm pretty sure you can use `operator |` just fine, e.g.,  `foo(..., sysrepo::EditOptions::Isolate | sysrepo::EditOptions::Strict, ...)`. Please reopen if it doesn't work for you.
