### ISSUE TITLE
Support of sr_lock()

### ISSUE THREAD

**Issue by rbu9fe** [sysrepo/sysrepo-cpp#19]
Sysrepo's C API features the `sr_lock()` function, with which race conditions can be avoided when multiple clients want to modify a datastore in parallel. With the locking mechanism there's a race condition in which the first changes may be overwritten by latter ones unintentionally. 
Would it be possible to implement that feature in the `Session` class?

**Comment by jktjkt** [comment]
how does https://gerrit.cesnet.cz/c/CzechLight/sysrepo-cpp/+/6671 look like?

**Comment by rbu9fe** [comment]
Thanks for your quick support!
