### ISSUE TITLE
Augmented predicates in Session::onModuleChange XPath

### ISSUE THREAD

**Issue by mitjarislakki** [sysrepo/sysrepo-cpp#25]
Hi!

I'm playing around with module_change_example.cpp prior to implementing my own plugin. Currently I have ietf-interfaces augmented by ieee802-dot1q-bridge & ieee802-dot1q-sched-bridge. I would like to filter interfaces to be those with supported-list-max>0.

In netopeer2-cli connected to netopeer2-server on the same machine, I am able to run

`get-config --source running --filter-xpath "/ietf-interfaces:interfaces/interface[ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/supported-list-max>0]"`

Which returns all interfaces fulfilling the predicate (e.g. br0). However, if I run module_change_example.cpp as

`./module_change_example ietf-interfaces "/ietf-interfaces:interfaces/interface[ieee802-dot1q-bridge:bridge-port/ieee802-dot1q-sched-bridge:gate-parameter-table/supported-list-max>0]"`

And send a simple change via netopeer2-cli  (gate-enabled was previously false)

`edit-config --target running --config=change.xml`

```XML
<interfaces xmlns="urn:ietf:params:xml:ns:yang:ietf-interfaces">
  <interface>
    <name>br0</name>
    <bridge-port xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-bridge">
      <gate-parameter-table xmlns="urn:ieee:std:802.1Q:yang:ieee802-dot1q-sched-bridge">
        <gate-enabled>true</gate-enabled>
      </gate-parameter-table>
    </bridge-port>
  </interface>
</interfaces>
```
The changes are applied but the example plugin does not print any information. With no xpath or xpath as `ietf-interfaces:interfaces/interface[name='br0']` module_change_example reacts to the changes as expected. Not sure whether this is directly related to sysrepo-cpp or the other libraries, or intended behavior in the first place but would highly appreciate some help.

Using most recent releases libyang 3.1.0, libnetconf2 3.3.3, sysrepo 2.10.1, netopeer2 2.2.28 & the following commits of sysrepo-cpp and libyang-cpp with libyang 3 support:
- https://gerrit.cesnet.cz/c/CzechLight/sysrepo-cpp/+/7330
- https://gerrit.cesnet.cz/c/CzechLight/libyang-cpp/+/7329

**Comment by jktjkt** [comment]
How does it behave when you run sysrepo's own `module_change_example` with the same parameters? If you're getting different results using the C++ example, please let us know and we'll investigate further. However, if it works the same using the C example from upstream sysrepo, then chances are that it's a bug/feature in how sysrepo-level implements XPath in subscriptions, and in that case please talk to upstream. I would say that the documentation on which XPath constructs are supported could be improved.

**Comment by mitjarislakki** [comment]
> How does it behave when you run sysrepo's own `module_change_example` with the same parameters? If you're getting different results using the C++ example, please let us know and we'll investigate further. However, if it works the same using the C example from upstream sysrepo, then chances are that it's a bug/feature in how sysrepo-level implements XPath in subscriptions, and in that case please talk to upstream. I would say that the documentation on which XPath constructs are supported could be improved.

Didn't notice the `application_changes_example` in sysrepo before, appears to act the same so I will bring it up upstream. Thanks!

**Comment by jktjkt** [comment]
closing in favor of https://github.com/sysrepo/sysrepo/issues/3362
