### ISSUE TITLE
Add SOVERSION to the shared lib

### ISSUE THREAD

**Issue by gotthardp** [sysrepo/sysrepo-cpp#5]
Would you please add SOVERSION to the shared library, just like sysrepo has (or somehow similarly)?
```cmake
set_target_properties(sysrepo PROPERTIES VERSION ${SYSREPO_SOVERSION_FULL} SOVERSION ${SYSREPO_SOVERSION})
```
Yocto Linux reports a "QA issue" that there is none.

**Comment by jktjkt** [comment]
Done.
