### ISSUE TITLE
`sysrepo::Subcription` is not default constructible

### ISSUE THREAD

**Issue by syyyr** [sysrepo/sysrepo-cpp#6]
Currently, the only way to have a `sysrepo::Subcription` as a member, is to either initialize it directly in class member initializer list, or make it into an `std::optional<sysrepo::Subcription>`.

The first solution is kind of undesirable, because it means that there is a lot of code in the member init-list. The second one means that sometimes, you may forget that to assign the optional on the first subscription (if you're doing multiple subscriptions).

**Comment by jktjkt** [comment]
I think this is something that we just have to live with.
