### ISSUE TITLE
Can Sysrepo-cpp be used with netopeer?

### ISSUE THREAD

**Issue by tarekgayoub** [sysrepo/sysrepo-cpp#9]
Hello,

I am working with netooper2 and I am wondering if sysrepo-cpp and libyang-cpp can be used with libnetconf2 and netopeer2?

I am looking to deploy netopeer2 in a c++ project and I want to ask how can I use the sysrep-cpp ?

Below is how I am starting the netconf server at the moment, can I use libyang-cpp and sysrepo-cpp instead of libyang and sysrepo?
```
sudo -i

mkdir NetConfServer
cd NetConfServer

#Install libyang
git clone https://github.com/CESNET/libyang.git
cd libyang
mkdir build && cd build && cmake .. && make && make install

#Install sysrepo
cd ..
git clone https://github.com/sysrepo/sysrepo.git
cd sysrepo
mkdir build && cd build && cmake .. && make && make install

# Install libnetconf2
cd ..
git clone https://github.com/CESNET/libnetconf2.git
cd libnetconf2
mkdir build && cd build && cmake .. && make && make install

# Install Netopeer2
cd ..
git clone https://github.com/CESNET/netopeer2.git
cd netopeer2
mkdir build && cd build && cmake -GENERATE_HOSTKEY=OFF -MERGE_LISTEN_CONFIG=OFF .. && make && make install

```

Thanks,

Tarek

**Comment by syyyr** [comment]
Hello,

Netopeer2 is a C program and so needs the C version of the libyang, sysrepo and libnetconf2 libraries. It is however possible have sysrepo-cpp (and libyang-cpp) installed alongside the C libraries.

I am not sure what you mean by deploying netopeer2 in a c++ project. Netopeer2 is a program, not a library.

Let me know if you have any more questions.
